### ISSUE TITLE
recursive option for monorepos

### ISSUE THREAD

**Issue by benmccann** [NullVoxPopuli/dependency-maintainers#9]
Svelte and SvelteKit are pnpm monorepos. It'd be cool if I could pass a `-r` option like I can do with the script in https://github.com/NullVoxPopuli/dependency-maintainers/issues/7#issuecomment-2192439452

**Comment by NullVoxPopuli** [comment]
I'm a big fan -- could use `@manypkg/get-packages` to iterate and simultaneously support yarn and npm as well

**Comment by NullVoxPopuli** [comment]
Implemented in https://github.com/NullVoxPopuli/dependency-maintainers/releases/tag/v1.1.0-dependency-maintainers
